AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.2
  Exclude:
    - 'db/schema.rb'

Metrics/LineLength:
  Max: 150

Style/EmptyLines:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/SpaceInsideBrackets:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: true
  Exclude:
    - 'bin/spring'

Style/FrozenStringLiteralComment:
  Enabled: false